# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea018ffa8cb8742e4de5bd0f4485c91533d20edc500df6805280e185dfd58a1ba11f668d9512dfa2870e253762279ff3f24f3b4f94cb886c03624136018ffdb3

test:
  secret_key_base: ac6f3c8554d57b96f70b3cf57041e6f17827d39d0a68e0fa507b5c4109e0ee43496d31e6ed42f500d44316ec8d7d24c054665fd71a0ee670489521225c08795e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
